#= require jquery
#= require jquery_ujs
#= require jquery.cookie
#= require jquery.equalheights
#= require bootstrap/bootstrap.min
#= require fancybox/jquery.fancybox
#= require jstree/jquery.jstree
#= require ./taxonomies_manager
#= require ./distal
#= require_self
